name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - inference-schema[numpy-support]
    - azure-ai-m
    - transformers
    - sentencepiece
    - pandas
    - numpy
